name: Deploy to S3 (Dry Run)

# Default to bash
defaults:
  run:
    shell: bash

on:
  workflow_dispatch

env:
  END_POINT: '${{ secrets.S3_END_POINT }}'
  ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}'
  SECRET_KEY: '${{ secrets.S3_SECRET_KEY }}'
  BUCKET_NAME: '${{ secrets.S3_BUCKET_NAME }}'
  VAULT: '${{ RUNNER_TEMP }}/obsidian-vault'
  HUGO_SITE: '${{ GITHUB_WORKSPACE }}/hugo-site'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Verify Environments
      run: |
        [[ -z "$END_POINT" ]] && echo "Provide END_POINT" && exit 1 
        [[ -z "$ACCESS_KEY" ]] && echo "Provide ACCESS_KEY" && exit 1 
        [[ -z "$SECRET_KEY" ]] && echo "Provide SECRET_KEY" && exit 1 
        [[ -z "$BUCKET_NAME" ]] && echo "Provide BUCKET_NAME" && exit 1 
    - name: Checkout with submodules
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.121.0"
        extended: true
    - name: Setup Hugo Site
      run: |
        # Create new site but keep config.yaml
        cd $HUGO_SITE
        mv hugo.yaml ../ && hugo new site . --force --format yaml && mv ../hugo.yaml ./hugo.yaml
        cd $GITHUB_WORKSPACE
        # Transpile obsidian contents
        chmod +x ./build.sh
        ./build.sh
    - name: Depoly to S3
      run: |
        chmod +x ./sync.sh
        ./sync --dry-run
